Result/or else
darklang/tablecloth pull request #176
Opened 2020-09-14 08:00 UTC by shubhamkumar13

Refer #162 
The bucklescript for Option directory already has an [`orElse`](https://github.com/darklang/tablecloth/blob/eca87dac1f2c3742526b67983b9da8a23f4bf3ba/bucklescript/src/TableclothOption.ml)

This PR tries to replicate the same functionality from `orElse`

2020-09-16 00:30 UTC, pbiggar requested changes
Great, thank you! Can you add some tests as well? Thanks!

2020-09-16 00:30 UTC, pbiggar commented on bucklescript/src/TableclothResult.mli
> +(** Return the first argument if it {isError} otherwise return second
```suggestion
(** Return the second argument if the first one is {!isError}, otherwise return the first
```

2020-09-16 14:54 UTC, pbiggar commented
Thanks! Can you take a look at the test failures in CI?

2020-09-16 15:22 UTC, shubhamkumar13 commented
@pbiggar out of the 6 build [tests](https://github.com/darklang/tablecloth/pull/176/checks?check_run_id=1123842781)
3 are failing and 3 are passing.
The 3 tests that are failing are related to a formatting issue which can be solved by using a formatting tool (helpful if you can share a link :smiley:  ).
The other 2 correspond to #175

2020-09-16 16:56 UTC, shubhamkumar13 commented
resolved format issues manually (tried using ocamlformat but it failed in files that weren't modified by me)
`make check-format` did the trick

2020-09-29 05:21 UTC, pbiggar commented
I added CircleCI support to main. Can you rebase this off main and if it passes CI, I'll merge it.

2021-08-17 14:56 UTC, closed without merging

2021-08-18 15:43 UTC, pbiggar commented
This was automatically closed when I deleted the master branch. Apologies, I'll circle back and see if I can get this merged.